Fix expansion of selective sync tree
owncloud/client pull request #10058
Opened 2022-08-24 12:50 UTC by fmoc

Before:
![screenshot_2022-08-24_14-47-12](https://user-images.githubusercontent.com/80399010/186422471-02eb4214-1cfc-4318-8359-cce1638eb236.png)

After:
![screenshot_2022-08-24_14-49-07](https://user-images.githubusercontent.com/80399010/186422490-f125e363-c3eb-42f0-990a-5e1bb8a42f3c.png)

2022-08-24 12:52 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12933/6/1

<details>


</details>


<!-- id: pr-10058 -->

2022-08-24 14:14 UTC, erikjv approved these changes

2022-08-24 14:57 UTC, fmoc commented
We decided to have another look.

2022-08-24 18:31 UTC, fmoc commented
I had another look and I think this new fix is significantly better than my last attempt. Now there is a check to make sure invalid `QVariant`s won't slip through the check.

2022-08-25 07:29 UTC, dragotin requested changes
The whole patch seems bogus since the isReady flag is always true. Why don't you remove the isReady flag completely? There is one more usage in `AccountSettings::slotCustomContextMenuRequested` which can be cleaned up/removed as well.

2022-08-25 09:48 UTC, dragotin commented
Currently, whenever you use `data( index, FolderStatusDelegate::IsReady)` you have access to the folder object as well. With that you could ask if the folder object is ready, which is what you're really interested in. Pulling that through the model makes that more complex in my opinion. 
So again, my recommendation is:  Drop the isReady from the model data and use `folder->isReady()` directly.

That removes alternative code pathes that actually do the same thing.

2022-08-25 10:06 UTC, fmoc commented
Makes sense, totally agree, thanks!

2022-08-25 10:08 UTC, erikjv approved these changes
Nice!

2022-08-25 10:31 UTC, dragotin approved these changes
LGTM

2022-08-25 10:44 UTC, merged