GitHub Workflows security hardening
owncloud/client pull request #10066
Opened 2022-08-27 22:09 UTC by sashashura

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

2022-08-27 22:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/client?pullRequest=10066) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/client?pullRequest=10066) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/client?pullRequest=10066) it.</sub>

2022-09-15 10:05 UTC, fmoc commented
First of all, the `permissions` key only applies to the `GITHUB_TOKEN` and therefore limits the access to the GitHub API. Therefore, changes to this key can prevent, e.g., unintentional writes, providing another "safety net". However, it doesn't really close any attack vectors, since third parties can always open PRs and change the values. Only in combination with GitHub's approval mechanism for first time contributors to run workflows on GitHub actions could reasonably protect the repository, but one could argue that the additional `permissions` doesn't provide any security gain over this, since in any case, changes must be reviewed before approving workflow runs.

There are use cases in which this change can help prevent security issues, though. For instance, tools running as part of the pipeline (including random third-party GitHub actions) cannot gain access to a token capable of writing while running as part of our workflows on our main branches, for instance. PR tokens are more limited than regular ones anyway

Right now, I cannot really tell whether the claims made in https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions apply. GitHub's docs aren't clear on this, and the document does not discuss PRs. However, as said, this can help in certain cases, and that justifies the inclusion of this change. I'll post a review asap.

2022-09-15 10:06 UTC, fmoc requested changes
No same-line comments, please. They're the root of all evil. Please move them above.

There is no need to document `none`, this is actually pretty obvious, and also the docs quickly reveal that information. What's good, however, is documenting why you need the `write` access, so please keep those comments.

2022-09-16 10:12 UTC, sashashura commented
Done, please take a look.

2022-09-16 13:50 UTC, fmoc approved these changes
Thanks!

2022-09-16 13:50 UTC, merged