Compatibility with older python3-nautilus
owncloud/client pull request #10075
Opened 2022-09-01 18:25 UTC by nteodosio

Quoting from [devhelp](https://tracker.debian.org/pkg/devhelp) (sorry, couldn't find a web document to link to), migrating Nautilus section:

>    The get_file_items, get_file_items_full, get_background_items a get_background_items_full methods of Nautilus.MenuProvider no longer take the window argument. Remove it from your implementations.
    If you need to keep supporting older versions of Nautilus, you can use variadic arguments:
```
  def get_file_items(self, *args):
      # `args` will be `[files: List[Nautilus.FileInfo]]` in Nautilus 4.0 API,
      # and `[window: Gtk.Widget, files: List[Nautilus.FileInfo]]` in Nautilus 3.0 API.
      files = args[-1]
```

2022-09-01 18:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/client?pullRequest=10075) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/client?pullRequest=10075) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/client?pullRequest=10075) it.</sub>

2022-09-06 15:17 UTC, fmoc requested changes
Please document this workaround in the code base as well, so we won't forget in the future why the files are queried from the packed parameters.

2022-09-06 15:18 UTC, fmoc commented
Your change looks good, but I'd like to have the reasoning documented in the code as well.

2022-09-07 08:31 UTC, fmoc approved these changes
Thanks!

2022-09-08 08:24 UTC, merged

2022-09-08 11:21 UTC, jbicha commented
Here's the weblink for the devhelp documentation:

https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html