Log when we get invoked by QSingleApplication
owncloud/client pull request #10086
Opened 2022-09-06 12:15 UTC by TheOneRing

Issue: #9988

2022-09-06 14:52 UTC, fmoc requested changes

2022-09-06 15:29 UTC, TheOneRing commented on src/gui/application.cpp
> +    const QLatin1String prefix("MSG_PARSEOPTIONS:");
ideally we should only define the string once, and use it here as well as in the main.cpp .
application_p.h?

2022-09-07 08:33 UTC, fmoc commented on src/gui/application.cpp
> +    const QLatin1String prefix("MSG_PARSEOPTIONS:");
Doesn't have to be a private header IMO, but yes, that would be great.

2022-09-13 11:59 UTC, fmoc requested changes

2022-09-13 11:59 UTC, fmoc commented on src/gui/application_p.h
> +    inline auto msgPareOptionsC()
```suggestion
    inline auto msgParseOptionsC()
```

```suggestion
    inline QString msgParseOptionsC()
```

2022-09-13 12:05 UTC, fmoc approved these changes

2022-09-13 12:10 UTC, merged