Spaces delegate
owncloud/client pull request #10091
Opened 2022-09-08 09:55 UTC by TheOneRing

![image](https://user-images.githubusercontent.com/200626/189093119-54b15227-b31f-4cb1-8071-d65d445aa89a.png)

2022-09-08 09:56 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13062/6/1

<details>


</details>


<!-- id: pr-10091 -->

2022-09-09 13:22 UTC, TheOneRing commented
![image](https://user-images.githubusercontent.com/200626/189359624-766c193d-26b7-4e7b-8c01-75e4270baf54.png)

2022-09-09 14:43 UTC, michaelstingl approved these changes
LGTM 👍

2022-09-12 17:09 UTC, fmoc requested changes

2022-09-12 17:09 UTC, fmoc commented on src/gui/spaces/spacesmodel.cpp
> +constexpr QSize ImageMarginC(ImageSizeC * 0.1);
Even though the image size is static, I'd rather not use a percentage. This is a float calculation that needs to be rounded. I'd rather use a static offset.

2022-09-13 07:29 UTC, TheOneRing commented on src/gui/spaces/spacesbrowser.ui
> +     <property name="wordWrap">
Its set to false

2022-09-13 07:51 UTC, TheOneRing commented on src/gui/spaces/spacesmodel.cpp
> +            return {};
I have to else the compiler will complain about an unnhandled case.
If we need an Image role we should probably invent one (no alias) similar to the underlying data role.

2022-09-13 07:53 UTC, TheOneRing commented on src/gui/spaces/spacesbrowser.ui
> +     <property name="wordWrap">
And it has an influence on the size hint

2022-09-13 11:32 UTC, fmoc approved these changes

2022-09-13 11:33 UTC, merged