More detailed debug logging
owncloud/client pull request #10094
Opened 2022-09-08 12:32 UTC by erikjv

2022-09-08 13:03 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13069/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/13069/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/13069/guiReportUpload/serverlog.log

Screenshots:
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/13069/guiReportUpload/screenshots/Delete_a_folder.png)
- [File_with_long_name_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/13069/guiReportUpload/screenshots/File_with_long_name_can_be_synced.png)
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/13069/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)

</details>


<!-- id: pr-10094 -->

2022-09-09 12:07 UTC, TheOneRing approved these changes

2022-09-09 12:34 UTC, fmoc requested changes

2022-09-12 11:14 UTC, fmoc approved these changes

2022-09-13 12:10 UTC, merged