Log duration of http requests
owncloud/client pull request #10142
Opened 2022-09-27 11:52 UTC by TheOneRing

```
09-27 13:49:44:033 [ info sync.httplogger ]:	"2c6286e0-8145-4167-82de-07546a5a6c6c: Response: GET 200 (duration(0h, 0min, 0s, 151ms)) https://ocis.owncloud.test/status.php Header: { Access-Control-Allow-Origin: *, Content-Length: 286, Content-Security-Policy: default-src 'none';, Content-Type: application/json, Date: Tue, 27 Sep 2022 11:49:44 GMT, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: [{\n    \"installed\": true,\n    \"maintenance\": false,\n    \"needsDbUpgrade\": false,\n    \"version\": \"10.11.0.0\",\n    \"versionstring\": \"10.11.0\",\n    \"edition\": \"Community\",\n    \"productname\": \"Infinite Scale\",\n    \"product\": \"Infinite Scale\",\n    \"productversion\": \"2.0.0-beta.8+a60b98c73\"\n}]"
```

2022-09-27 12:53 UTC, michaelstingl approved these changes
Nice, we can try if this helps us to understand some things… 🤞

2022-09-27 13:53 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13256/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/13256/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/13256/guiReportUpload/serverlog.log

Screenshots:
- [Syncing_all_files_and_folders_from_the_server.png](https://cache.owncloud.com/public/owncloud/client/13256/guiReportUpload/screenshots/Syncing_all_files_and_folders_from_the_server.png)
- [change_collaborator_permissions_of_a_file_&_folder.png](https://cache.owncloud.com/public/owncloud/client/13256/guiReportUpload/screenshots/change_collaborator_permissions_of_a_file_&_folder.png)

</details>


<!-- id: pr-10142 -->

2022-10-04 15:28 UTC, fmoc requested changes

2022-10-05 14:26 UTC, fmoc commented on src/libsync/httplogger.cpp
> +    QObject::connect(reply, &QNetworkReply::finished, reply, [reply, start] {
You should document this then so that it won't get lost. I didn't think of that.

2022-10-05 14:32 UTC, TheOneRing commented on src/libsync/httplogger.cpp
> +    QObject::connect(reply, &QNetworkReply::finished, reply, [reply, start] {
I don't care

2022-10-06 23:23 UTC, fmoc approved these changes

2022-10-07 06:28 UTC, merged