WIP: Sort spaces
owncloud/client pull request #10158
Opened 2022-10-04 11:52 UTC by TheOneRing

2022-10-04 11:53 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13316/6/1

<details>


</details>


<!-- id: pr-10158 -->

2022-10-28 14:20 UTC, fmoc approved these changes

2022-10-28 14:38 UTC, fmoc requested changes
Please fix the build.

2022-10-31 11:03 UTC, fmoc approved these changes

2022-10-31 11:03 UTC, merged