Draft: Fix start-on-login again
owncloud/client pull request #10178
Opened 2022-10-11 15:03 UTC by erikjv

2022-10-11 15:33 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/13377/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/13377/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/13377/guiReportUpload/serverlog.log

Screenshots:
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/13377/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)

</details>


<!-- id: pr-10178 -->

2022-10-12 14:34 UTC, TheOneRing approved these changes

2022-10-12 14:47 UTC, TheOneRing requested changes
Please run clang format and change the title.

2022-10-13 07:45 UTC, TheOneRing requested changes
Please fix the commit message

2022-10-17 16:21 UTC, fmoc commented on src/common/utility_mac.mm
> +            if (enable) {
This flag is called `launch` in the function's docstring. This should be corrected/updated (both signature and docstring).

2022-10-18 12:04 UTC, TheOneRing commented on src/gui/platform.cpp
> +{
Why should we log that we did nothing?

2022-10-18 12:04 UTC, TheOneRing commented on src/gui/application.cpp
> +    platform->migrate();
In the mac constructor

2022-10-18 12:37 UTC, merged