Don't prevent sync on unknown servers
owncloud/client pull request #10308
Opened 2022-11-23 14:46 UTC by TheOneRing

Fixes: #9737

2022-11-23 15:11 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/13763/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/13763/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/13763/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Both_original_and_copied_folders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/13763/oc10/guiReportUpload/screenshots/Both_original_and_copied_folders_can_be_synced.png)
- [login_after_loggin_out.png](https://cache.owncloud.com/public/owncloud/client/13763/oc10/guiReportUpload/screenshots/login_after_loggin_out.png)

</details>


<!-- id: pr-10308-oc10 -->

2022-11-24 14:23 UTC, fmoc requested changes

2022-11-24 14:23 UTC, fmoc commented on src/libsync/account.cpp
> +Account::ServerSupportLevel Account::serverVersionUnsupported() const
I think the method name should be adjusted, e.g., `serverSupportLevel`. The old name is misleading now.

2022-11-24 14:35 UTC, fmoc approved these changes

2022-11-24 14:40 UTC, merged