Log parseables
owncloud/client pull request #10310
Opened 2022-11-23 17:40 UTC by dragotin

Changes the log format to:
```
22-11-23 18:38:34:438 [ info sync.httplogger ]: "5dca3f29-99a7-488b-a35d-8113302e4ba8: Response: PROPFIND 207 (duration(0h, 0min, 0s, 214ms)=214ms) ht...
```
Note 
1. The year at the beginning of the line to make the time stamp standard compatible and parseable
2. The duration in milliseconds appended to the "verbose" duration for humans...

2022-11-24 10:20 UTC, fmoc requested changes

2022-11-24 10:20 UTC, fmoc commented on src/libsync/httplogger.cpp
> +        stream << duration << "=" << int_ms.count() << "ms)";
```suggestion
        const auto durationInMs = std::chrono::duration_cast<std::chrono::milliseconds>(duration);
        stream << durationInMs.count() << "ms)";
```

Logging the duration once is more than sufficient.

2022-11-24 16:16 UTC, dragotin commented
Yes, I think logging it once is sufficient, but @TheOneRing wanted to have the human readable version as well when she first checked it...

2022-11-25 09:57 UTC, merged

2022-11-25 10:38 UTC, dragotin commented
Thanks for pulling that to 3.0 !