Fix the version string for released builds
owncloud/client pull request #10329
Opened 2022-11-30 18:39 UTC by TheOneRing

2022-11-30 18:50 UTC, dschmidt requested changes

2022-11-30 18:50 UTC, dschmidt commented on changelog/unreleased/10329
> +We removed a training - in the version string of released clients.
```suggestion
We removed a trailing `-` in the version string of released clients.
```

2022-11-30 19:18 UTC, fmoc approved these changes

2022-11-30 19:26 UTC, dschmidt approved these changes

2022-12-01 11:45 UTC, fmoc approved these changes

2022-12-01 11:49 UTC, merged