Add an option to trigger a reconnect
owncloud/client pull request #10370
Opened 2022-12-21 14:52 UTC by TheOneRing

Fixes: #10294

2022-12-21 15:02 UTC, fmoc requested changes
I'd move the button below the log out one.

2022-12-21 15:02 UTC, fmoc commented on src/gui/accountsettings.cpp
> +        _toggleReconnect->setVisible(!_accountState->isConnected());
Please keep it visible at all times but disable it when it's not needed.

2022-12-22 12:45 UTC, fmoc approved these changes

2022-12-22 12:45 UTC, merged

2023-01-05 09:30 UTC, TheOneRing commented
Testing:
- Start the client
- Interrupt the internet connection
- Force sync or wait 1 minute
- Client should display timeouts and the reconnect button in the accounts menu is enabled
- Restore the connection
- Use reconnect button or wait 5-10 minutes.