Fix duplicate acct: in Webfinger resource ID
owncloud/client pull request #10478
Opened 2023-02-07 11:54 UTC by fmoc

The WebFinger class expects a resource ID already. It's the caller's job to assemble the `acct:` URL, not WebFinger's.

2023-02-07 11:57 UTC, fmoc commented
Fixed version of #10476.

2023-02-07 11:59 UTC, TheOneRing requested changes
Don't remove `toPercentEncoding`

2023-02-07 12:15 UTC, TheOneRing approved these changes

2023-02-07 12:34 UTC, merged

2023-03-22 07:16 UTC, saw-jan commented
Tested in https://github.com/owncloud/client/issues/10471#issuecomment-1426202976