Fix custom user ID and hint handling
owncloud/client pull request #10480
Opened 2023-02-07 14:59 UTC by fmoc

![image](https://user-images.githubusercontent.com/80399010/217279205-ad645818-0b32-4bb9-ac4e-f3c4a9246f10.png)

![screenshot_2023-02-07_15-49-47](https://user-images.githubusercontent.com/80399010/217279242-1da4667d-ecd3-4099-a17f-6cfa571a6f98.png)

Fixes #10440.

Do we need changelog entries for these changes?

2023-02-07 15:27 UTC, TheOneRing requested changes

2023-02-07 15:27 UTC, TheOneRing commented on src/gui/loginrequireddialog/basicloginwidget.cpp
> -    if (!Theme::instance()->userIDHint().isEmpty()) {
Why was this removed

2023-02-07 16:20 UTC, TheOneRing approved these changes

2023-02-07 16:41 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14221/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14221/oc10/guiReportUpload/screenshots/Delete_a_folder.png)

</details>


<!-- id: pr-10480-oc10 -->

2023-02-07 16:46 UTC, merged

2023-03-24 09:07 UTC, HanaGemela commented
Still broken in qa 4.0.0.10487-alpha1

2023-03-24 14:27 UTC, HanaGemela commented
Passed in qa 4.0.0.10497-alpha1, mac