Hide 'Disable virtual file support' option when vfs options are set to hidden
owncloud/client pull request #10521
Opened 2023-02-21 13:14 UTC by TheOneRing

2023-02-21 13:39 UTC, ownclouders commented
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14357/7/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/serverlog.log
Stacktrace: https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/stacktrace.log

Screenshots:
- [File_with_long_name_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/File_with_long_name_can_be_synced.png)
- [File_with_spaces_in_the_name_can_sync.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/File_with_spaces_in_the_name_can_sync.png)
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)
- [Modify_orignal_content_of_a_file_with_special_character.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/Modify_orignal_content_of_a_file_with_special_character.png)
- [Syncing_a_file_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/Syncing_a_file_to_the_server.png)
- [Syncing_file_of_1_GB_size.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/Syncing_file_of_1_GB_size.png)
- [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)
- [User_with_Editor_role_can_edit_the_file.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/User_with_Editor_role_can_edit_the_file.png)
- [User_with_Manager_role_can_add_files_and_folders.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/User_with_Manager_role_can_add_files_and_folders.png)
- [various_types_of_files_can_be_synced_from_client_to_server.png](https://cache.owncloud.com/public/owncloud/client/14357/ocis/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_client_to_server.png)

</details>


<!-- id: pr-10521-ocis -->

2023-02-24 11:19 UTC, fmoc requested changes

2023-02-24 11:19 UTC, fmoc commented on changelog/unreleased/enterprise-5612
> +Bugfix: Handle showVirtualFilesOption as disableVirtual files
That space within `disableVirtual files` looks like a typo.

2023-02-24 13:50 UTC, fmoc requested changes

2023-02-24 13:50 UTC, fmoc commented on changelog/unreleased/enterprise-5612
> +Bugfix: Handle showVirtualFilesOption as disableVirtualFiles
That would be `!showVirtualFilesOption`, right?

2023-02-28 09:29 UTC, fmoc approved these changes

2023-02-28 09:30 UTC, merged