Correctly display connection state
owncloud/client pull request #10558
Opened 2023-03-02 11:14 UTC by TheOneRing

2023-03-02 11:30 UTC, ownclouders commented
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14479/7/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14479/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14479/ocis/guiReportUpload/serverlog.log

Screenshots:
- [logging_out.png](https://cache.owncloud.com/public/owncloud/client/14479/ocis/guiReportUpload/screenshots/logging_out.png)
- [login_after_loggin_out.png](https://cache.owncloud.com/public/owncloud/client/14479/ocis/guiReportUpload/screenshots/login_after_loggin_out.png)

</details>


<!-- id: pr-10558-ocis -->

2023-03-02 11:40 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14479/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14479/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14479/oc10/guiReportUpload/serverlog.log

Screenshots:
- [logging_out.png](https://cache.owncloud.com/public/owncloud/client/14479/oc10/guiReportUpload/screenshots/logging_out.png)
- [login_after_loggin_out.png](https://cache.owncloud.com/public/owncloud/client/14479/oc10/guiReportUpload/screenshots/login_after_loggin_out.png)

</details>


<!-- id: pr-10558-oc10 -->

2023-03-03 04:19 UTC, saw-jan commented
The failure is due to the change in the text.

Before:
![Screenshot from 2023-03-03 10-02-33](https://user-images.githubusercontent.com/52366632/222630287-e04a50a7-1e76-4ea0-ae27-01210ef351bd.png)

this PR:
![Screenshot from 2023-03-03 10-02-42](https://user-images.githubusercontent.com/52366632/222630311-1e100bc5-be91-4509-b1b2-d6376b6e695e.png)


Is it the intended change?

2023-03-03 04:24 UTC, saw-jan commented
@TheOneRing I have adapted the tests according to the new text changes. If that was not the intended change then please remove my commit.

2023-03-03 12:24 UTC, fmoc requested changes

2023-03-06 15:27 UTC, fmoc approved these changes
Played a bit with the code, seems to work.

2023-03-06 15:27 UTC, fmoc commented on changelog/unreleased/10557
> +Introduce new state, `Connecting to`.
We split the current "no connection configured" state into a "disconnected" and "connecting to" state to better explain the client's behavior to the user.

2023-03-06 15:27 UTC, fmoc commented on src/gui/accountsettings.cpp
> +    for (auto *folder : folderMan->folders()) {
```suggestion
    // in 2023 there should never be credentials encoded in the url, but we never know...
    const auto safeUrl = account->url().adjusted(QUrl::RemoveUserInfo);

    FolderMan *folderMan = FolderMan::instance();
    for (auto *folder : folderMan->folders()) {
```

2023-03-07 09:09 UTC, merged