Wip
owncloud/client pull request #10575
Opened 2023-03-07 14:01 UTC by TheOneRing

2023-03-07 14:27 UTC, ownclouders commented
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14552/7/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/serverlog.log

Screenshots:
- [Add_space_manually_from_sync_connection_window.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Add_space_manually_from_sync_connection_window.png)
- [Adding_account_with_vfs_enabled.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Adding_account_with_vfs_enabled.png)
- [Both_original_and_copied_folders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Both_original_and_copied_folders_can_be_synced.png)
- [Delete_a_file_and_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Delete_a_file_and_a_folder.png)
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Delete_a_folder.png)
- [Enable_VFS.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Enable_VFS.png)
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)
- [Invalid_system_names_are_synced_in_linux.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Invalid_system_names_are_synced_in_linux.png)
- [Many_subfolders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Many_subfolders_can_be_synced.png)
- [Move_folder_and_file_from_level_5_sub-folder_to_sync_root.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Move_folder_and_file_from_level_5_sub-folder_to_sync_root.png)
- [Move_two_folders_and_a_file_down_to_the_level_5_sub-folder.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Move_two_folders_and_a_file_down_to_the_level_5_sub-folder.png)
- [Rename_a_file_and_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Rename_a_file_and_a_folder.png)
- [Syncing_a_folder_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Syncing_a_folder_to_the_server.png)
- [Syncing_all_files_and_folders_from_the_server.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Syncing_all_files_and_folders_from_the_server.png)
- [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)
- [User_with_Manager_role_can_add_files_and_folders.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/User_with_Manager_role_can_add_files_and_folders.png)
- [Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png)
- [Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png)
- [Verify_that_you_can_create_a_subfolder_with_long_name.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/Verify_that_you_can_create_a_subfolder_with_long_name.png)
- [various_types_of_files_can_be_synced_from_server_to_client.png](https://cache.owncloud.com/public/owncloud/client/14552/ocis/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_server_to_client.png)

</details>


<!-- id: pr-10575-ocis -->

2023-03-07 15:00 UTC, TheOneRing commented on src/libsync/owncloudpropagator.cpp
>                  // all is good, the rename will be executed before the directory deletion
this part is really fishy, first I thought it was missing a continue but I think the condition was just to prevent the warning

2023-03-07 15:37 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14558/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Adding_account_with_vfs_enabled.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/Adding_account_with_vfs_enabled.png)
- [Enable_VFS.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/Enable_VFS.png)
- [Rename_a_file_and_a_folder.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/Rename_a_file_and_a_folder.png)
- [Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png)
- [Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png)
- [share_file_and_folder_to_a_group.png](https://cache.owncloud.com/public/owncloud/client/14558/oc10/guiReportUpload/screenshots/share_file_and_folder_to_a_group.png)

</details>


<!-- id: pr-10575-oc10 -->

2023-03-08 10:52 UTC, TheOneRing commented on src/libsync/owncloudpropagator.cpp
> +                Q_ASSERT(!removeDirectoryJob);
It appears that we might set removeDirectoryJob  multiple times, I assume it is a clever part of an algorithm.
removeDirectoryJob  is accessed in 402

2023-03-17 11:12 UTC, fmoc requested changes

2023-03-17 11:12 UTC, fmoc commented on changelog/unreleased/9311
> +Bugfix: Don't abort local folder delets on unrelated errors
```suggestion
Bugfix: Don't abort local folder deletions on unrelated errors
```

Alternatively:
```suggestion
Bugfix: Don't abort local folder deletes on unrelated errors
```

2023-03-17 11:12 UTC, fmoc commented on changelog/unreleased/9311
> +We fixed a bug where folder deletes where not performed if any sync error
```suggestion
We fixed a bug where folder deletions where not performed if any sync error
```

2023-03-17 13:06 UTC, merged