Overlay status icons over base icon
owncloud/client pull request #10606
Opened 2023-03-16 15:42 UTC by fmoc

This way, we do not need to provide pre-rendered icons to depict the different synchronization states but can dynamically overlay small icons over the base application icon.

As a fallback, the existing setup will continue to be supported: as long as an icon called "base" is not found, the lookup assumes the overlay icon filename contains a pre-rendered icon and therefore returns it unmodified.

2023-03-16 15:44 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14664/6/1

<details>


</details>


<!-- id: pr-10606-oc10 -->

2023-03-21 08:34 UTC, TheOneRing commented
Please fix your commits before review...

2023-03-21 09:02 UTC, fmoc commented
This branch can be squash-merged just fine. I can also squash it upon approval in a matter of seconds. I'm not sure what advantage you see in squashing in advance of a review.

2023-03-21 09:22 UTC, TheOneRing requested changes
Code is not ready for review

2023-03-21 10:47 UTC, TheOneRing commented on src/libsync/overlayiconengine.cpp
> +    // TODO: copied from qsvgiconengine
```suggestion
    // Based on qsvgiconengine, compute a dpi aware scaled size
```

2023-03-21 10:53 UTC, TheOneRing requested changes

2023-03-21 10:53 UTC, TheOneRing commented on src/libsync/theme.cpp
> +        if (baseIcon.isNull()) {
We could unify the code paths minimally.

2023-03-21 10:53 UTC, TheOneRing commented on src/resources/core_theme.qrc
> +
The file was formated by qt creator, not sure manual formatting is a good idea.

2023-03-21 10:53 UTC, TheOneRing commented on src/resources/theme/colored/sidebar.svg
its either the preview or we had a color change, why was that icon touched at all?

2023-03-23 10:27 UTC, TheOneRing commented on src/libsync/overlayiconengine.cpp
> +    img.fill(0);
Qt::transparent

2023-03-23 14:30 UTC, TheOneRing commented
Lets discuss next week

2024-02-08 08:38 UTC, closed without merging