Server theme support
owncloud/client pull request #10617
Opened 2023-03-21 11:01 UTC by fmoc

Support server-side provided theme as described in https://github.com/owncloud/ocis/issues/5513.

Depends on #10626. Should eventually fix https://github.com/owncloud/client/issues/10519.

Related: https://github.com/owncloud/ocis/issues/5754

2023-03-21 11:37 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14706/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14706/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14706/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Syncing_a_folder_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/14706/oc10/guiReportUpload/screenshots/Syncing_a_folder_to_the_server.png)
- [share_a_file_with_many_users.png](https://cache.owncloud.com/public/owncloud/client/14706/oc10/guiReportUpload/screenshots/share_a_file_with_many_users.png)

</details>


<!-- id: pr-10617-oc10 -->

2023-03-23 10:29 UTC, TheOneRing requested changes

2023-03-23 10:29 UTC, TheOneRing commented on src/gui/servertheme.h
> +        Light = Default,
Why the aliases?

2023-03-27 15:00 UTC, fmoc commented on src/gui/accountstate.cpp
> +    connect(this, &AccountState::stateChanged, this, [this](State state) {
I didn't find this to be doable in any other state, but please feel free to suggest alternatives!

2023-03-27 16:20 UTC, fmoc commented on src/gui/accountsettings.cpp
> +        const auto &icon = _accountState->serverThemeIcon();
Not sure what you mean, please elaborate.

2024-02-08 08:37 UTC, closed without merging