Move getCoreIcon to the resource module
owncloud/client pull request #10624
Opened 2023-03-22 15:39 UTC by TheOneRing

We already require a QGuiApplication so keeping the core free of QGui doesn't make much sense.
This change will allow to use resources in libsync.

2023-03-22 16:07 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14718/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14718/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14718/oc10/guiReportUpload/serverlog.log

Screenshots:
- [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/14718/oc10/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)

</details>


<!-- id: pr-10624-oc10 -->

2023-04-04 08:54 UTC, fmoc requested changes

2023-04-04 08:54 UTC, fmoc commented on src/resources/resources.h
> +namespace Resources {
```suggestion
namespace OCC::Resources {
```

2023-04-04 08:54 UTC, fmoc commented on src/resources/resources.h
> +} // Resources
```suggestion
} // OCC::Resources
```

2023-04-04 09:56 UTC, fmoc approved these changes

2023-04-04 09:57 UTC, merged