Spaces image in delegate
owncloud/client pull request #10623
Opened 2023-03-22 13:41 UTC by TheOneRing

Fixes: #10041

2023-03-22 13:45 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14716/6/1

<details>


</details>


<!-- id: pr-10623-oc10 -->

2023-03-22 13:45 UTC, ownclouders commented
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14716/7/1

<details>


</details>


<!-- id: pr-10623-ocis -->

2023-04-13 14:18 UTC, fmoc requested changes

2023-04-13 14:18 UTC, fmoc commented on src/libsync/graphapi/space.cpp
> +        auto job = _spaceManager->account()->resourcesCache()->makeGetJob(imageUrl(), {}, this);
Still not a fan of this "lazy loading", but it'll do for now.

2023-04-13 14:32 UTC, TheOneRing commented on src/libsync/graphapi/space.h
> +        QIcon image() const;
Not a null icon but a fallback

2023-04-13 14:59 UTC, fmoc approved these changes

2023-04-13 15:00 UTC, merged