[gui-tests] Update expected oauth2 login successful message
owncloud/client pull request #10676
Opened 2023-04-06 06:50 UTC by saw-jan

2023-04-06 07:07 UTC, ownclouders commented
Results for <strong>GUI-tests-ocis</strong> https://drone.owncloud.com/owncloud/client/14857/7/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/serverlog.log
Stacktrace: https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/stacktrace.log

Screenshots:
- [Adding_account_with_vfs_enabled.png](https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/screenshots/Adding_account_with_vfs_enabled.png)
- [Adding_multiple_accounts.png](https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/screenshots/Adding_multiple_accounts.png)
- [Adding_normal_Account.png](https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/screenshots/Adding_normal_Account.png)
- [Try_to_enable_experimental_vfs_option_and_cancel_it.png](https://cache.owncloud.com/public/owncloud/client/14857/ocis/guiReportUpload/screenshots/Try_to_enable_experimental_vfs_option_and_cancel_it.png)

</details>


<!-- id: pr-10676-ocis -->

2023-04-06 07:20 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14857/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14857/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14857/oc10/guiReportUpload/serverlog.log
Stacktrace: https://cache.owncloud.com/public/owncloud/client/14857/oc10/guiReportUpload/stacktrace.log

Screenshots:
- [login_with_oauth2_enabled.png](https://cache.owncloud.com/public/owncloud/client/14857/oc10/guiReportUpload/screenshots/login_with_oauth2_enabled.png)

</details>


<!-- id: pr-10676-oc10 -->

2023-04-06 07:53 UTC, saw-jan commented
> Results for **GUI-tests-oc10** https://drone.owncloud.com/owncloud/client/14857/6/1
> 
> boom The GUI tests failed.
> 
> GUI Logs: https://cache.owncloud.com/public/owncloud/client/14857/oc10/guiReportUpload/index.html

```bash
FATAL - AUT Crashed
  Test 'tst_loginLogout' aborted because the AUT crashed
  Process /drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /tmp/owncloud-client/ exited abnormally, return code -1:
  Received signal number 6.. Dumped core.
ERROR - Script Error
LookupError: Lost connection to AUT
```
Existing AUT crash error: https://github.com/owncloud/client/issues/10675

2023-04-12 04:29 UTC, individual-it approved these changes

2023-04-12 08:04 UTC, TheOneRing requested changes
Please don't merge, I think this is a bug.

2023-04-12 08:46 UTC, saw-jan commented
> It appears the issue is fixed by #10692

I will close this here. Thanks for noticing

2023-04-12 08:46 UTC, closed without merging