Fix setup of OAuth2 accounts
owncloud/client pull request #10684
Opened 2023-04-06 13:56 UTC by fmoc

It's not great to add the setter to the common interface, but still much better than casting the pointer and conditionally executing that method.

Fixes #10682.

2023-04-06 13:58 UTC, TheOneRing approved these changes

2023-04-06 14:10 UTC, ownclouders commented
Results for <strong>GUI-tests-oc10</strong> https://drone.owncloud.com/owncloud/client/14866/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/14866/oc10/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/14866/oc10/guiReportUpload/serverlog.log
Stacktrace: https://cache.owncloud.com/public/owncloud/client/14866/oc10/guiReportUpload/stacktrace.log

Screenshots:
- [login_with_oauth2_enabled.png](https://cache.owncloud.com/public/owncloud/client/14866/oc10/guiReportUpload/screenshots/login_with_oauth2_enabled.png)

</details>


<!-- id: pr-10684-oc10 -->

2023-04-06 14:15 UTC, TheOneRing requested changes
Ci says no. Please test manually.

2023-04-11 03:33 UTC, saw-jan commented
> Ci says no. Please test manually.

AUT crashes with oc10 server. Also, the authorization successful message has changed so the oauth2 login test will fail. If it is an inteded change, this is the PR to change the test code https://github.com/owncloud/client/pull/10676

2023-04-11 15:06 UTC, merged