Use theme methods instead of macros for application name
owncloud/client pull request #10812
Opened 2023-05-05 15:54 UTC by erikjv

And also for the application icon name. There is one left in the common sources, but those cannot depend on libsync, so that's left alone.

2023-05-09 09:11 UTC, TheOneRing commented
I assume there is are a few more. In general you could check to not include config.h which should only be needed in one or two locations the rest should rely on theme.h

2023-05-11 14:38 UTC, erikjv commented
Note: `guiutility_mac.mm` is still a problem

2023-05-12 10:13 UTC, erikjv commented
> Note: `guiutility_mac.mm` is still a problem

I left two uses of defines in there, as they are mac specific.

2023-05-23 14:29 UTC, TheOneRing commented
```
owncloud-client [work/get-app-name-from-theme ≡ +3 ~0 -0 !]> git grep "config.h"
src/common/plugin.cpp:#include "config.h"
src/csync/CMakeLists.txt:configure_file(config.h.in ${CMAKE_CURRENT_BINARY_DIR}/config.h)
src/csync/csync_exclude.cpp:#include "config.h"
src/gui/folderwatcher_linux.cpp:#include "config.h"
src/gui/guiutility_mac.mm:#include "config.h"
src/gui/libcloudproviders/libcloudproviders.cpp:#include "config.h"
src/gui/lockwatcher.h:#include "config.h"
src/gui/main.cpp:#include "csync/config.h"
src/gui/socketapi/socketapi.h:#include "config.h"
src/gui/updater/updater.cpp:#include "config.h"
src/libsync/configfile.cpp:#include "config.h"
src/libsync/filesystem.h:#include "config.h"
src/libsync/theme.cpp:#include "config.h"
test/testsyncvirtualfiles.cpp:#include "config.h"
test/testutility.cpp:#include "config.h"

2023-05-31 12:19 UTC, TheOneRing requested changes

2023-05-31 12:19 UTC, TheOneRing commented on src/gui/systray.cpp
> +        QList<QVariant> args = QList<QVariant>() << Theme::instance()->appNameGUI() << quint32(0) << Theme::instance()->applicationIcon() << title << message
This used to be a QString, we now send a QIcon, I don't think that will work.

2023-05-31 13:06 UTC, erikjv commented
This fixes https://github.com/owncloud/client/issues/10461

2023-05-31 13:24 UTC, TheOneRing approved these changes

2023-05-31 13:41 UTC, merged