Add unit test added a year ago to cmake
owncloud/client pull request #10828
Opened 2023-05-09 15:48 UTC by TheOneRing

2023-05-09 16:02 UTC, fmoc approved these changes

2023-05-09 16:03 UTC, fmoc requested changes

2023-05-09 16:07 UTC, TheOneRing commented on test/testupdater.cpp
> -    void testVersionToInt()
That code was remove month ago

2023-05-09 16:41 UTC, fmoc approved these changes

2023-06-02 14:28 UTC, fmoc approved these changes

2023-06-02 14:28 UTC, merged