Handle "selected sync destination is unusable" case better in setup wizard
owncloud/client pull request #11029
Opened 2023-07-12 09:30 UTC by fmoc

Fixes #10680.

2023-07-12 10:17 UTC, michaelstingl approved these changes
Works for me 👍

2023-07-12 10:54 UTC, TheOneRing commented on src/gui/newwizard/setupwizardcontroller.h
> +
Q_ENUM...

2023-07-12 10:55 UTC, TheOneRing commented on src/gui/newwizard/setupwizardcontroller.cpp
> +            auto page = dynamic_cast<AccountConfiguredWizardPage *>(_currentState->page());
```suggestion
            auto *page = dynamic_cast<AccountConfiguredWizardPage *>(_currentState->page());
```

2023-07-12 10:56 UTC, TheOneRing commented on src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp
> +    auto defaultSyncTargetDir = _context->accountBuilder().defaultSyncTargetDir();
```suggestion
    QString defaultSyncTargetDir = _context->accountBuilder().defaultSyncTargetDir();
```

2023-07-12 10:57 UTC, TheOneRing requested changes
^

2023-07-21 11:05 UTC, TheOneRing requested changes
ci

2023-07-21 14:59 UTC, TheOneRing approved these changes

2023-07-21 15:11 UTC, merged