Backport: Include mtime in tus Upload-Metadata (#10958)
owncloud/client pull request #11087
Opened 2023-08-04 14:25 UTC by TheOneRing

2023-08-04 14:33 UTC, fmoc approved these changes

2023-08-04 14:33 UTC, fmoc requested changes
CI complains.

2023-08-04 15:26 UTC, fmoc approved these changes

2023-08-04 15:27 UTC, merged

2023-08-07 08:35 UTC, HanaGemela commented
Passed in ownCloud 4.2.0.11667-daily20230807, mac. There is mtime in Upload metadata, the file on the server has it's original time when it was created. Tested against  Infinite Scale 3.1.0-rc.1+9f6067e4b Community