wip fix vfs issues
owncloud/client pull request #11138
Opened 2023-08-22 13:09 UTC by TheOneRing

2023-08-30 12:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/client?pullRequest=11138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/client?pullRequest=11138) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: TheOneRing<br/>:x: ownclouders<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/client?pullRequest=11138) it.</sub>

2023-08-30 14:22 UTC, TheOneRing commented on test/testsyncconflict.cpp
> +
```suggestion
```

2023-08-30 14:22 UTC, TheOneRing commented on src/libsync/progressdispatcher.h
> +
```suggestion
```

2023-09-04 09:47 UTC, fmoc requested changes

2023-09-05 14:09 UTC, fmoc approved these changes

2023-09-05 17:53 UTC, merged