Fix crash in network job destructor
owncloud/client pull request #11211
Opened 2023-09-15 10:53 UTC by TheOneRing

Fixes: #11203

2023-09-15 11:22 UTC, fmoc approved these changes

2023-09-15 11:23 UTC, fmoc requested changes

2023-09-15 11:23 UTC, fmoc commented on src/libsync/graphapi/spacesmanager.cpp
> +    // leak the job until we fixed the onwership https://github.com/owncloud/client/issues/11203
```suggestion
    // TODO: leak the job until we fixed the onwership https://github.com/owncloud/client/issues/11203
```

2023-09-15 11:23 UTC, fmoc approved these changes

2023-09-15 12:02 UTC, fmoc commented
Looks like the Nautilus plugin is causing problems again:
```
Initializing ownCloud-client-nautilus extension
Using python version sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Could not connect to unix socket /tmp/runtime-headless/ownCloud/socket. [Errno 111] Connection refused
13:39:17:482 Info: Connection to 127.0.0.1:54086 closed.
```

Let's merge this PR nevertheless and see if this is just a temporary issue. Otherwise, @saw-jan can try to fix this next week.

2023-09-15 12:02 UTC, merged

2023-09-21 04:12 UTC, saw-jan commented
> Could not connect to unix socket /tmp/runtime-headless/ownCloud/socket. [Errno 111] Connection refused

I believe this is expected as the error is thrown due to the initialization of `SocketConnection` before the desktop-client is up in https://github.com/owncloud/client-desktop-shell-integration-nautilus/blob/ebde52785c72b3688d157bb791ef0f37389aa431/src/syncstate.py#L176
Initialization happens whenever the file is loaded. so we get `Could not connect to unix socket` error. And as per Squish, I think, it resets and reloads everything per test suite (i.e. per `tst_<suite-name>` folder). So, I would expect to get atleast 11 such error