Work/fix switching vfs
owncloud/client pull request #11395
Opened 2023-11-23 10:43 UTC by TheOneRing

2023-11-30 15:24 UTC, erikjv requested changes

2023-11-30 15:48 UTC, TheOneRing commented on src/gui/folder.cpp
> +                    qDebug() << "miau";
🙈 😹

2023-12-01 14:26 UTC, erikjv approved these changes

2023-12-01 15:17 UTC, merged

2023-12-13 12:20 UTC, HanaGemela commented
Fixed in 6.0.0 alpha 1