Strip user info from URL in New Connection Wizard
owncloud/client pull request #11509
Opened 2024-02-06 15:10 UTC by erikjv

Authentication is done through the web browser, so no user information is needed for that URL.

Fixes: #11497

2024-02-06 15:23 UTC, TheOneRing commented
Changelog please

2024-02-13 14:36 UTC, TheOneRing requested changes
^

2024-02-19 12:41 UTC, erikjv commented
> ^

done

2024-02-20 08:43 UTC, TheOneRing approved these changes

2024-02-20 08:43 UTC, merged