Add update information to the about dialog
owncloud/client pull request #11541
Opened 2024-03-11 16:56 UTC by erikjv

Fixes: #11486

2024-03-11 16:58 UTC, erikjv commented
I'm not sure if we should move everything from the settings dialog to the about dialog. I think we should move the update part in the settings up higher, because it's probably more used than bandwidth limits. 

For the about dialog: the text is customisable, so I added a label about the update status. We should probably also add a button or link text to redirect to the settings when there is an update available.

2024-03-14 16:49 UTC, TheOneRing commented
Hmm the channel selection is only available in testpilotcloud so maybe we can move it to the about dialog?

2024-03-18 13:05 UTC, erikjv commented
> Hmm the channel selection is only available in testpilotcloud so maybe we can move it to the about dialog?

We can. I think it would give theming/design problems if we put it in the "about" tab, so maybe make a new (second) tab called "Updates" and put the contents of the QGroupBox in there? Also, I introduced that label at the bottom to draw more attention to updates, should that label stay? (See screenshot below.)

<img width="809" alt="Screenshot 2024-03-18 at 14 03 41" src="https://github.com/owncloud/client/assets/151956/f8cfc74f-95b7-4501-a561-8d06970c9bf9">

2024-03-19 08:47 UTC, TheOneRing commented
I think only the text can be branded, so it should be possible to add the info into the main widget.

2024-03-27 16:39 UTC, erikjv commented
In the latest commit I moved all of the update stuff from the settings dialog to the about dialog. @TheOneRing How can I test this?

2024-04-05 14:51 UTC, erikjv commented
<img width="781" alt="Screenshot 2024-04-05 at 16 51 05" src="https://github.com/owncloud/client/assets/151956/ab6b8c91-9418-4e46-a47c-80e575951f2b">

I'm not sure if I can get the version number out. I think it'd be useful to show that too.

2024-04-05 14:55 UTC, erikjv commented
@TheOneRing  The `OCUpdater` could provide the version. Should I add that in a separate PR?

2024-04-05 15:12 UTC, TheOneRing requested changes

2024-04-05 15:12 UTC, TheOneRing commented on src/gui/aboutdialog.cpp
> +#include "configfile.h"
could you use the full paths please?

2024-04-05 15:12 UTC, TheOneRing commented on src/gui/aboutdialog.h
> +private slots:
```suggestion
private Q_SLOTS:
```

2024-04-08 12:06 UTC, erikjv commented on src/gui/aboutdialog.cpp
> +#include "configfile.h"
done

2024-04-08 12:06 UTC, erikjv commented on src/gui/aboutdialog.h
> +private slots:
done

2024-04-08 12:07 UTC, erikjv commented
> I'm not sure if I can get the version number out. I think it'd be useful to show that too.

So that was during testing. Meaning it passed the testing.

2024-04-08 12:46 UTC, merged