Show "Enable VFS" option after disableing VFS
owncloud/client pull request #11738
Opened 2024-07-09 13:02 UTC by erikjv

Fixes: #11566

2024-09-05 11:38 UTC, erikjv commented
In the scenario above, we should also show the enable option

2024-09-24 13:23 UTC, TheOneRing commented
![image](https://github.com/user-attachments/assets/070ac109-ad4e-4626-9a94-42ec4c69d88f)
![image](https://github.com/user-attachments/assets/49e2b685-cf57-4033-aadf-b4013b92413f)

There is no action displayed at all

2024-09-24 13:24 UTC, TheOneRing requested changes
^

2024-09-26 10:22 UTC, TheOneRing approved these changes

2024-09-26 10:23 UTC, merged