PropfindJob::finishedWithError don't pass raw network request
owncloud/client pull request #11770
Opened 2024-07-31 09:18 UTC by TheOneRing

2024-07-31 09:19 UTC, TheOneRing commented on src/libsync/networkjobs.cpp
> -        if (reply()->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt() != 207) {
Handled in https://github.com/owncloud/client/blob/2639a9a79b1c350f95308ef8c672ef9538941d8c/src/libsync/networkjobs.cpp#L302-L302

2024-08-01 16:18 UTC, erikjv requested changes

2024-08-01 16:18 UTC, erikjv commented on src/gui/selectivesyncwidget.cpp
> +            _loading->setText(tr("No subfolders currently on the server."));
Please rephrase: "Currently there are no subfolders on the server."

2024-08-01 16:18 UTC, erikjv commented on src/gui/selectivesyncwidget.cpp
> +            _loading->setText(tr("An error occurred while loading the list of sub folders."));
AFAIK we use "subfolders" (one word, see above), not "sub folders".

2024-08-02 09:28 UTC, erikjv approved these changes

2024-08-02 09:55 UTC, merged