Selective sync: hide child indicator for a childless folder
owncloud/client pull request #11917
Opened 2024-10-01 15:21 UTC by erikjv

Fixes: #8935

2024-10-02 10:13 UTC, TheOneRing commented on src/gui/selectivesyncwidget.cpp
> +        recursiveInsert(item, pathTrail, path, size, showChildIndicator);
Could you add a comment how showChildIndicator works in this recursion?
As it isn't changed, I'd expect it to define the indicator for the whole sub tree.

2024-10-02 10:13 UTC, TheOneRing requested changes
^

2024-10-02 14:42 UTC, TheOneRing approved these changes

2024-10-02 14:43 UTC, erikjv commented on src/gui/selectivesyncwidget.cpp
> +void SelectiveSyncWidget::recursiveInsert(QTreeWidgetItem *parent, QStringList pathTrail, QString path, qint64 size, bool showChildIndicator)
Explain how the recursive algorithm works

2024-10-10 14:30 UTC, erikjv commented on src/gui/selectivesyncwidget.cpp
> +void SelectiveSyncWidget::recursiveInsert(QTreeWidgetItem *parent, QStringList pathTrail, QString path, qint64 size, bool showChildIndicator)
done

2024-10-14 14:20 UTC, TheOneRing approved these changes

2024-10-14 14:39 UTC, merged