Fix button alignment in oauth screen
owncloud/client pull request #11923
Opened 2024-10-08 13:04 UTC by erikjv

When an item is in a layout, the width property is ignored, and the implicitWidth is used. So the copy-to-clipboard button's preferredWidth should be bound the implicitWidth property of the open-browser button.

Fixes: #11915

2024-10-08 23:50 UTC, DeepDiver1975 commented
Kind of works ..... please make sure every element stays in proper shape. THX

![Screenshot from 2024-10-09 01-48-33](https://github.com/user-attachments/assets/e1449c07-5bc4-4344-940d-f2a8fb5331d5)
![Screenshot from 2024-10-09 01-48-39](https://github.com/user-attachments/assets/cb140507-616b-4e60-bc5d-854bf45eb332)

2024-10-10 06:45 UTC, DeepDiver1975 requested changes
alignment with sign out button is missing

2024-10-10 12:06 UTC, erikjv commented
@TheOneRing As with #11924 : how can I set that on the logout button?

2024-10-14 08:27 UTC, TheOneRing commented
> @TheOneRing As with #11924 : how can I set that on the logout button?

reauth

2024-10-14 08:28 UTC, TheOneRing commented
And https://github.com/owncloud/client/blob/49ae25f2bc560d21958619f96ddac9c0b706cf3e/src/gui/qml/credentials/Credentials.qml#L38-L59

2024-10-15 14:02 UTC, closed without merging