Draft: Fix tab order in basic auth login screen
owncloud/client pull request #11924
Opened 2024-10-09 14:18 UTC by erikjv

Fixes: #11912

2024-10-09 14:22 UTC, erikjv commented
1. not handling the event seems to "drop" it
2. trying to pass it to the parent doesn't seem to work
3. manually handling tab focus fails, because I cannot seem to get hold of the item/button for the logout component

Maybe we should always show the logout button, and use the visibility to show/hide it? Or have a dummy item at the bottom which forwards the focus to the widget when it gets tab focus?

2024-10-14 09:54 UTC, TheOneRing requested changes

2024-10-14 09:54 UTC, TheOneRing commented on src/gui/qml/credentials/BasicAuthCredentials.qml
>                  widget.parentFocusWidget.focusNext();
shouldn't parentFocusWidget be able to take care?

2024-10-14 09:54 UTC, TheOneRing commented on src/gui/qml/credentials/BasicAuthCredentials.qml
> +            event.accepted = true;
https://doc.qt.io/qt-6/qml-qtquick-keys.html#example-usage

2024-10-15 13:51 UTC, closed without merging