Fix tab order in basic auth login screen
owncloud/client pull request #11930
Opened 2024-10-15 13:58 UTC by erikjv

Fixes: #11912

2024-10-15 14:05 UTC, TheOneRing commented on src/gui/qml/credentials/BasicAuthCredentials.qml
> +        Layout.preferredWidth: userNameField.implicitWidth
Wrong pr?

2024-10-15 14:09 UTC, erikjv commented
Title has been updated to reflect that these are 3 commits fixing multiple issues.

2024-10-15 14:19 UTC, TheOneRing commented on src/gui/qml/credentials/BasicAuthCredentials.qml
> +        Layout.preferredWidth: userNameField.implicitWidth
As we also have 3 issues for that those also need linking

2024-10-15 14:20 UTC, TheOneRing submitted a review, later dismissed
Lgtm

2024-10-15 14:22 UTC, DeepDiver1975 requested changes
one pr to fix one issue please

2024-10-15 14:57 UTC, erikjv commented
It's now split up

2024-10-16 10:02 UTC, TheOneRing approved these changes

2024-10-16 10:02 UTC, merged