Remove unnecessary stripping of leading slashes
owncloud/client pull request #8526
Opened 2021-03-25 14:18 UTC by fmoc

Once the slash is gone, an assert is triggered, making the software terminate unexpectedly:

```
[...] [ fatal default ]: ASSERT: "relativePath.startsWith(QLatin1Char('/'))" in file .../client/src/libsync/abstractnetworkjob.cpp, line 196
```

This happens when trying to add a directory synchronization, in the second step where the remote directory is selected, once you click on the next button.

Related to #8459.

2021-03-25 14:20 UTC, TheOneRing commented
do things break if its not a root path? 
/foo/bar/ for example :)

2021-03-25 14:21 UTC, fmoc commented
Yes, I've tried subdirectories as well, e.g., `/Documents`. The leading slash is stripped, and the software crashes.

2021-03-25 14:30 UTC, TheOneRing approved these changes

2021-03-26 11:17 UTC, TheOneRing requested changes
See https://github.com/owncloud/client/blob/master/src/gui/folder.h#L161 so we need to remove the trailing slash, BUT not if we only have /

2021-03-26 11:18 UTC, TheOneRing approved these changes

2021-03-26 20:53 UTC, fmoc commented
This is about the unnecessary removal of a leading, not a trailing slash. I don't think there'll be any issues with trailing slashes.

2021-03-29 14:41 UTC, merged