Ensure the tests are properly set up
owncloud/client pull request #8857
Opened 2021-08-02 09:28 UTC by TheOneRing

2021-08-02 10:25 UTC, dschmidt requested changes
as testutilsloader.cpp is now compiled into every test and testutils have their own CMakeLists.txt file, to me testutilsloader.cpp should not be in the testutils folder.

apart from that, LGTM

2021-08-02 10:34 UTC, TheOneRing commented
> 
> 
> as testutilsloader.cpp is now compiled into every test and testutils have their own CMakeLists.txt file, to me testutilsloader.cpp should not be in the testutils folder.
> 
> apart from that, LGTM

Hm but its part of the test utils and not a test itself, I'm trying to not fill the root folder by way more files than required....

2021-08-02 11:05 UTC, dschmidt commented
I don't think that's really an issue, all tests start with "test" prefix anyway. 
In doubt create an additional folder, but don't mix the lib and externally compiled in files, that's very confusing imho.

2021-08-03 15:24 UTC, fmoc commented on test/owncloud_add_test.cmake
> +    ecm_add_test(test${OWNCLOUD_TEST_CLASS_LOWERCASE}.cpp ${PROJECT_SOURCE_DIR}/test/testutils/testutilsloader.cpp ${ARGN}
Please add a comment that you cannot put this file into a library because that breaks that Qt macro so we don't forget in the future.

2021-08-03 15:26 UTC, TheOneRing commented
It is really part of the testutils and not part of the test..
@fmoc suggested https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries but that's not supported on the platforms we support....
I'm currently try to not drop all src we got in to one single folder...

2021-08-03 15:26 UTC, fmoc commented
If you prefer some sort of CMake library that is then added as a dependency to the target, there are [object libraries](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries) which are relatively similar to other types of libraries within CMake. They are relatively new, though, so we'd need to bump the CMake minimum required version.

I don't really find this confusing, to be honest, as long as the reason why it's done like this from now on is documented in the relevant places within the code.

2021-08-04 07:11 UTC, TheOneRing commented
Happy?

2021-08-04 07:14 UTC, merged