WIP: Align sync status icons
owncloud/client pull request #8858
Opened 2021-08-02 13:30 UTC by TheOneRing

With this change we will display the problem state if we have blacklisted errors.
This change also aligns the icon in the tray icon with the icon displayed for the folder state.

![image](https://user-images.githubusercontent.com/200626/127869675-7f68ec0a-70e9-423e-998b-467ec22dfc2f.png)

2021-08-02 14:23 UTC, TheOneRing commented
![image](https://user-images.githubusercontent.com/200626/127876784-c801352e-e12f-4a96-b608-4b0fb165c62b.png)

2021-08-04 14:34 UTC, michaelstingl reviewed
Changes the "works as designed" behaviour explained in https://github.com/owncloud/client/issues/2432

2021-08-04 14:41 UTC, michaelstingl approved these changes
I think this is a good change 👍

2021-08-05 16:35 UTC, fmoc requested changes

2021-08-05 16:35 UTC, fmoc commented on src/gui/folderman.h
> +    void setStatus(SyncResult::Status status);
Do we really need this setter? I think you could set the overall status within `addResult` by remembering the "worst" status you've seen so far, right?

2021-08-05 16:35 UTC, fmoc commented on src/gui/folderman.h
> +    static QString trayTooltipStatusString(const SyncResult &syncStatus, bool paused);
Just like above, the variable should be called `*result`.

2021-08-05 16:35 UTC, fmoc commented on src/libsync/theme.cpp
> +        }
We need to do something about the formatter here. The placing of these braces is misleading. I needed to read it a second time to see that it's constructing a new object.

2021-08-05 16:35 UTC, fmoc commented on src/libsync/theme.h
> +    QIcon syncStateIcon(const SyncResult &status, bool sysTray = false, bool sysTrayMenuVisible = false) const;
Consider renaming the first param to `result`.

2021-08-06 11:24 UTC, fmoc approved these changes

2021-08-06 11:38 UTC, merged

2021-09-09 14:17 UTC, avrhack commented
I think this is a massive mistake - I have loads of deliberately ignored files and hidden files which I choose not to sync, so the client always shows the icon instead of success which is completely misleading. This should not happen where the 'errors' are warnings caused by specific user choices that are known about.

2021-09-09 14:38 UTC, TheOneRing commented
@avrhack Please see the discussion in https://github.com/owncloud/client/issues/8970 hidden files won't display the i icon.

2021-09-09 14:52 UTC, avrhack commented
> @avrhack Please see the discussion in #8970 hidden files won't display the i icon.

Thanks Hannah - I think that discussion just confirms my point; this change is a huge step backwards.

You say hidden files won't display the icon but all my errors are either hidden or ignored files and the icon DOES show so I'm afraid I have to respectively disagree with you. The icon should not be showing in this circumstance but it is.

I've had to revert to 2.8.2 as 2.9.0 is now unusable for me with this 'enhancement' and from that discussion others feel the same.

2021-09-13 13:19 UTC, s1mm0n commented
Also this seems to affect VFS.

All Virtual Files will be shown as "ignored" with the yellow icon.

MacOS 11.5.1 - Client 2.9.0 Build 5150

![image](https://user-images.githubusercontent.com/60744681/133090702-9b40b4a0-965e-4001-a8ca-9225e02dd964.png)

2021-09-13 13:51 UTC, TheOneRing commented
Can you check whether there is a file2.jpeg.owncloud on your server? Stuff like that used to happen in the past.
If not please open a new issue and don't comment on pull requests.