Fix qrand leftover
owncloud/client pull request #9181
Opened 2021-10-28 13:09 UTC by TheOneRing

2021-11-17 16:47 UTC, erikjv requested changes

2021-11-17 16:47 UTC, erikjv commented on src/libsync/propagateuploadng.cpp
> +    _transferId = uint(QRandomGenerator::global()->generate()) ^ uint(_item->_modtime) ^ (uint(_item->_size) << 16) ^ qHash(_item->_file);
Yeah, I think that can be removed.

2021-11-25 12:06 UTC, dschmidt approved these changes
:tada:

2021-11-25 16:20 UTC, dschmidt approved these changes

2021-11-25 16:27 UTC, merged