macOS: allow for debug builds in xcode-build
owncloud/client pull request #9211
Opened 2021-11-11 15:51 UTC by erikjv

Propagate the cmake build type to xcode-build too. Previously, a release
build would always be done. Now, a debug build will be done when the
cmake build type is Debug.

2021-11-11 16:12 UTC, TheOneRing approved these changes

2021-11-11 17:42 UTC, dschmidt requested changes
The first change is a must, the second doesn't matter in this case but I think it's better to consistently quote strings :)

2021-11-11 17:42 UTC, dschmidt commented on shell_integration/MacOSX/CMakeLists.txt
> +if (${CMAKE_BUILD_TYPE} EQUAL "Debug")
```suggestion
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
```
or
```suggestion
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
```

2021-11-11 17:42 UTC, dschmidt commented on shell_integration/MacOSX/CMakeLists.txt
> +        -target FinderSyncExt -configuration ${XCODE_CONFIG} "SYMROOT=${CMAKE_CURRENT_BINARY_DIR}"
```suggestion
        -target FinderSyncExt -configuration "${XCODE_CONFIG}" "SYMROOT=${CMAKE_CURRENT_BINARY_DIR}"
```

2021-11-12 11:37 UTC, erikjv commented on shell_integration/MacOSX/CMakeLists.txt
> +if (${CMAKE_BUILD_TYPE} EQUAL "Debug")
done

2021-11-12 11:38 UTC, erikjv commented on shell_integration/MacOSX/CMakeLists.txt
> +        -target FinderSyncExt -configuration ${XCODE_CONFIG} "SYMROOT=${CMAKE_CURRENT_BINARY_DIR}"
done

2021-11-12 15:47 UTC, dschmidt approved these changes

2021-11-12 16:27 UTC, merged