[Tests-Only][WIP] Fixed tests related to expiration date set/change
owncloud/client pull request #9463
Opened 2022-02-22 11:06 UTC by Talank

2022-02-24 10:54 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10881/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10881/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10881/guiReportUpload/serverlog.log)

2022-02-24 11:45 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10883/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10883/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10883/guiReportUpload/serverlog.log)

2022-02-28 08:02 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10908/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10908/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10908/guiReportUpload/serverlog.log)

2022-02-28 08:57 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10909/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10909/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10909/guiReportUpload/serverlog.log)

2022-03-01 11:59 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10925/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10925/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10925/guiReportUpload/serverlog.log)

2022-03-02 11:43 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/10933/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/10933/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/10933/guiReportUpload/serverlog.log)

2022-03-11 07:14 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11019/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11019/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11019/guiReportUpload/serverlog.log)

2022-03-11 07:33 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11020/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11020/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11020/guiReportUpload/serverlog.log)

2022-03-11 09:35 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11022/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11022/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11022/guiReportUpload/serverlog.log)

2022-03-11 10:17 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11024/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11024/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11024/guiReportUpload/serverlog.log)

2022-03-11 10:42 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11027/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11027/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11027/guiReportUpload/serverlog.log)

2022-03-11 11:17 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11030/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11030/guiReportUpload/index.html)            
Server Logs: ((https://cache.owncloud.com/public/owncloud/client/11030/guiReportUpload/serverlog.log)

2022-03-24 05:35 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11185/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png)
- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)
- [user_changes_the_expiration_date_of_an_already_existing_public_link_for_file_using_client-UI.png](https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/screenshots/user_changes_the_expiration_date_of_an_already_existing_public_link_for_file_using_client-UI.png)
- [user_changes_the_expiration_date_of_an_already_existing_public_link_for_folder_using_client-UI.png](https://cache.owncloud.com/public/owncloud/client/11185/guiReportUpload/screenshots/user_changes_the_expiration_date_of_an_already_existing_public_link_for_folder_using_client-UI.png)

2022-03-24 06:33 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11194/5/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11194/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11194/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/11194/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)

2022-04-13 07:25 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11433/6/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11433/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11433/guiReportUpload/serverlog.log)
Screenshots:
- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/11433/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)

<!-- id: pr-9463 -->

2022-05-05 07:14 UTC, Talank commented
I tried setting `"LC_TIME": "de_DE.UTF-8",` in Environment while running swuish. However, the format is still set to `en_US.UTF-8` according to the screenshot generated.

2022-05-16 07:03 UTC, Talank commented
All the test are now passing: https://drone.owncloud.com/owncloud/client/11770

2022-05-16 07:11 UTC, Talank commented on .drone.star
> +                             "LC_TIME": "de_DE.UTF-8",
Setting environment like this is not working for some reason. I will remove it.

2022-05-16 09:43 UTC, Talank commented on .drone.star
> +                             "LC_TIME": "de_DE.UTF-8",
May be this sets environment for squishrunner only, and not for squishserver!!! 🤔 Otherwise it should have worked

2022-05-17 06:32 UTC, saw-jan commented on test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
> +                    )
`actualDate` will not get updated here so you have to recalculate again. Also maybe throw from here if the dates are not equal (the test is going to fail anyway).

2022-05-17 09:30 UTC, Talank commented
Looks like 2 of the scenarios are still flaky. REF: https://cache.owncloud.com/public/owncloud/client/11783/guiReportUpload/index.html
- user changes the expiration date of an already existing public link for file using client-UI
- user changes the expiration date of an already existing public link for folder using client-UI

2022-05-17 12:01 UTC, saw-jan reviewed
LGTM

2022-05-18 05:30 UTC, Talank commented
> Looks like 2 of the scenarios are still flaky. REF: [drone build](https://drone.owncloud.com/owncloud/client/11783/6/14) and [gui report](https://cache.owncloud.com/public/owncloud/client/11783/guiReportUpload/index.html)
> 
> * [user changes the expiration date of an already existing public link for file using client-UI](https://cache.owncloud.com/public/owncloud/client/11783/guiReportUpload/screenshots/user_changes_the_expiration_date_of_an_already_existing_public_link_for_file_using_client-UI.png)
> * [user changes the expiration date of an already existing public link for folder using client-UI](https://cache.owncloud.com/public/owncloud/client/11783/guiReportUpload/screenshots/user_changes_the_expiration_date_of_an_already_existing_public_link_for_folder_using_client-UI.png)
> 
> **STRANGE!!** the failed screenshots show that the expiration date has been changed properly (the expected date after edit is `2038-07-21`). But failed while performing assertion from middleware. May be another syncing issue thinking

These 2 scenario are still flaky, so I will skip it in this PR, I will open a new issue to investigate why they are flaky.

2022-05-18 06:08 UTC, Talank commented
> Results for **GUI-tests** https://drone.owncloud.com/owncloud/client/11800/6/1 boom The GUI tests failed. GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11800/guiReportUpload/index.html) Server Logs: (https://cache.owncloud.com/public/owncloud/client/11800/guiReportUpload/serverlog.log) Stacktrace: (https://cache.owncloud.com/public/owncloud/client/11800/guiReportUpload/stacktrace.log) Screenshots:
> 
> * [remove_an_account_connection.png](https://cache.owncloud.com/public/owncloud/client/11800/guiReportUpload/screenshots/remove_an_account_connection.png)
> * [remove_the_only_account_connection.png](https://cache.owncloud.com/public/owncloud/client/11800/guiReportUpload/screenshots/remove_the_only_account_connection.png)

remove account crash (known issue https://github.com/owncloud/client/issues/9367) restarting CI build

2022-05-18 09:55 UTC, individual-it requested changes

2022-05-18 09:55 UTC, individual-it commented on test/gui/tst_sharing/test.feature
> +    @issue-9321 @skip
why changing that around?

2022-05-18 09:55 UTC, individual-it commented on test/gui/tst_sharing/test.feature
> +    @issue-9321 @skip
looks not needed

2022-05-18 10:24 UTC, individual-it approved these changes

2022-05-18 11:04 UTC, merged