[tests-only] Fix share with multiple users GUI test
owncloud/client pull request #9509
Opened 2022-03-11 10:14 UTC by saw-jan

This PR adds a check for whether the share is complete or not before closing the share dialog.

Fixes https://github.com/owncloud/client/issues/9429

2022-03-14 11:10 UTC, Talank reviewed
LGTM

2022-03-15 03:08 UTC, individual-it requested changes

2022-03-15 03:08 UTC, individual-it commented on test/gui/shared/scripts/pageObjects/SharingDialog.py
> +                "type": "QLabel",
I think name and type should not be hardcoded here

2022-03-15 09:24 UTC, individual-it approved these changes

2022-03-15 09:31 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/11074/5/1
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/11074/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/11074/guiReportUpload/serverlog.log)

2022-03-15 10:05 UTC, merged