Fix filter menus
owncloud/client pull request #9513
Opened 2022-03-11 14:42 UTC by erikjv

- replaced "No filter" option text with "All", to avoid the "No filter
  is not enabled" situation
- replace the "Filter" label on the button with "1 Filter"/"2 Filters"
  when a filter is active, so a user can immediately see that without
  having to open the filter pop-up

2022-03-11 14:55 UTC, TheOneRing commented on src/gui/issueswidget.cpp
> +    int filterCount = _statusSortModel->filterCount();
I can't really follow what why count here and why we increase it if the regexp is empty.
Could you add a comment?

2022-03-11 14:57 UTC, TheOneRing commented on changelog/unreleased/9513
> +
Add a url to this pr

2022-03-11 15:49 UTC, TheOneRing commented on changelog/unreleased/9513
> +https://github.com/owncloud/client/issues/9425
Maybe merge the entry with 9425?

2022-03-11 17:53 UTC, TheOneRing requested changes
As discussed

2022-03-11 19:11 UTC, erikjv commented
sigh. something weird happened with this MR. Should be fine now.

2022-03-14 10:04 UTC, TheOneRing commented on src/gui/protocolwidget.cpp
> +        return tr("Filter");
Hmm https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

2022-03-14 10:21 UTC, merged