fixed test for `Sync only one folder from the server`
owncloud/client pull request #9816
Opened 2022-06-23 08:56 UTC by sushmita56

This PR refactors the test related to the `account connection wizard`. The wizard of client version 3.0 is somewhat different than version 2.10. In version 3.0, the `choose_what_to_sync` button appears only when we select the `Configure synchronization manually` option in the advanced section. Also, the folders to be synced don't appear in a single tree selector. So here we're fixing the test for `Scenario: Sync only one folder from the server` in the `tst_syncing` suite to match the selectors in the new client version.

Related issue:
#9762

2022-06-23 09:26 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12197/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/serverlog.log

Screenshots:
- [Both_original_and_copied_folders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Both_original_and_copied_folders_can_be_synced.png)
- [File_with_long_name_(>228_characters)_is_blacklisted.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/File_with_long_name_(>228_characters)_is_blacklisted.png)
- [File_with_long_name_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/File_with_long_name_can_be_synced.png)
- [File_with_spaces_in_the_name_can_sync.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/File_with_spaces_in_the_name_can_sync.png)
- [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)
- [Invalid_system_names_are_synced_in_linux.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Invalid_system_names_are_synced_in_linux.png)
- [Many_subfolders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Many_subfolders_can_be_synced.png)
- [Sync_only_one_folder_from_the_server.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Sync_only_one_folder_from_the_server.png)
- [Syncing_a_folder_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Syncing_a_folder_to_the_server.png)
- [Syncing_file_of_1_GB_size.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Syncing_file_of_1_GB_size.png)
- [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)
- [Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png)
- [Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png)
- [Verify_that_you_can_create_a_subfolder_with_long_name.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/Verify_that_you_can_create_a_subfolder_with_long_name.png)
- [change_collaborator_permissions_of_a_file_&_folder.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/change_collaborator_permissions_of_a_file_&_folder.png)
- [sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/sharing_a_folder_by_public_link_with_"Uploader"_role_and_check_if_file_can_be_downloaded.png)
- [sharing_of_a_file_by_public_link_and_deleting_the_link.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/sharing_of_a_file_by_public_link_and_deleting_the_link.png)
- [sharing_of_a_file_by_public_link_with_password_and_changing_the_password.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/sharing_of_a_file_by_public_link_with_password_and_changing_the_password.png)
- [simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png)
- [simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png)
- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)
- [simple_sharing_of_file_and_folder_by_public_link_with_password.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_password.png)
- [simple_sharing_of_file_and_folder_by_public_link_without_password.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_without_password.png)
- [simple_sharing_of_folder_by_public_link_with_different_roles.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/simple_sharing_of_folder_by_public_link_with_different_roles.png)
- [various_types_of_files_can_be_synced_from_client_to_server.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_client_to_server.png)
- [various_types_of_files_can_be_synced_from_server_to_client.png](https://cache.owncloud.com/public/owncloud/client/12197/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_server_to_client.png)

</details>


<!-- id: pr-9816 -->

2022-07-05 11:07 UTC, saw-jan reviewed
https://drone.owncloud.com/owncloud/client/12335/6/14
CI Build time is longer than usual. Please, recheck all the failures locally.

2022-07-11 04:54 UTC, saw-jan reviewed
LGTM

2022-07-11 05:55 UTC, individual-it requested changes

2022-07-11 05:55 UTC, individual-it commented on test/gui/tst_syncing/test.feature
>          When the user selects the following folders to sync:
```suggestion
        When the user selects configure_synchronization_manually option in advanced section
        And the user "Alice" clicks on the next button in sync connection wizard
        And the user selects "ownCloud" as a remote destination folder
        And the user selects the following folders to sync:
```

2022-07-11 07:16 UTC, individual-it approved these changes

2022-07-11 08:53 UTC, merged