Implement Webfinger protocol in setup wizard
owncloud/client pull request #9841
Opened 2022-06-30 15:21 UTC by fmoc

Based on #9779. Uses the protocol implementation from https://github.com/owncloud/client/pull/9366. Contributes to #9249.

Opened as a draft because this requires some more cleanup and the error handling could be a little more user friendly.

Tested against the customer's production system.

2022-06-30 15:24 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12273/6/1

<details>


</details>


<!-- id: pr-9841 -->

2022-07-07 14:05 UTC, TheOneRing requested changes
Webfinger is supposed to be optional and depending on a branding parameter.

2022-07-07 14:05 UTC, TheOneRing commented on src/gui/newwizard/states/webfingersetupwizardstate.cpp
> +    //    _context->accountBuilder().setWebFingerData(QStringLiteral("acct:bla@example.org"), QUrl(QStringLiteral("https://oauth.example.org")));
cleanup?

2022-07-08 10:56 UTC, TheOneRing requested changes
`07-08 12:55:22:576 [ fatal default ]:	ENSURE: "webFinger->href().isEmpty()" in file /Users/hannah/ownbuild/master/downloads/`

2022-07-08 12:12 UTC, fmoc commented
I'll handle that error more gracefully.

2022-07-14 07:58 UTC, TheOneRing commented
The user name is the user name and should not contain the webfinger api prefix.
![image](https://user-images.githubusercontent.com/200626/178932032-8a2619bb-c6db-4c3b-829f-a42531c1cda5.png)

2022-07-14 07:59 UTC, TheOneRing requested changes
⬆️

2022-07-14 09:34 UTC, fmoc commented
You must be using an old state. This has been fixed. https://github.com/owncloud/client/pull/9841/files#diff-fb7667184e5f26f7b04f378cf8d0971deb76e2ffe35f18d138d8eb103494aabbR61

2022-07-14 10:05 UTC, TheOneRing commented
> You must be using an old state. This has been fixed. https://github.com/owncloud/client/pull/9841/files#diff-fb7667184e5f26f7b04f378cf8d0971deb76e2ffe35f18d138d8eb103494aabbR61

You are right.

However please set the dav password when we initialize the oauth workflow, this ensures that the id entered by the user is passed to the idp/oauth2 and the user is not asked to enter the id again.

2022-07-29 09:07 UTC, merged