Register defaultSyncRoot with the socket api
owncloud/client pull request #9845
Opened 2022-07-01 09:47 UTC by TheOneRing

The socked api won't populate the conext menu for the directory
but in every other regard it will behave like an ownCloud managed dir.

Fixes: #9838

2022-07-01 11:43 UTC, fmoc commented on src/gui/socketapi/socketapi.cpp
> +QString unegisterpathMessage()
```suggestion
const QString UnegisterPathMessage()
```

2022-07-01 12:34 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12302/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12302/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12302/guiReportUpload/serverlog.log

Screenshots:
- [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/12302/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)

</details>


<!-- id: pr-9845 -->

2022-07-05 08:07 UTC, fmoc requested changes

2022-07-05 08:07 UTC, fmoc commented on src/gui/socketapi/socketapi.cpp
> +const QString unegisterpathMessageC()
```suggestion
const QString unregisterpathMessageC()
```

2022-07-05 08:10 UTC, fmoc commented on src/gui/socketapi/socketapi.cpp
> +    broadcastMessage(buildMessage(unegisterpathMessageC(), Utility::stripTrailingSlash(folder->path()), QString()), true);
```suggestion
    broadcastMessage(buildMessage(unregisterpathMessageC(), Utility::stripTrailingSlash(folder->path()), QString()), true);
```

2022-07-05 08:10 UTC, fmoc commented on src/gui/socketapi/socketapi.cpp
> +        broadcastMessage(buildMessage(unegisterpathMessageC(), Utility::stripTrailingSlash(a->defaultSyncRoot())));
```suggestion
        broadcastMessage(buildMessage(unregisterpathMessageC(), Utility::stripTrailingSlash(a->defaultSyncRoot())));
```

2022-07-05 08:20 UTC, fmoc approved these changes

2022-07-05 08:23 UTC, merged