Throttle ui updates
owncloud/client pull request #9863
Opened 2022-07-05 16:17 UTC by TheOneRing

Issue: #9832

2022-07-05 16:28 UTC, TheOneRing commented
Some of the stuff in there really needs to run on an item level.
I have to take another look

2022-07-05 17:02 UTC, dragotin requested changes
Almost nice :)

2022-07-05 17:02 UTC, dragotin commented on src/gui/folderstatusmodel.cpp
> +            if (std::chrono::system_clock::now() - *progressUpdated > progressUpdateTimeOutC) {
Hm, I suggest using QElapsedTimer class. More clean imho.

2022-07-06 09:36 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12357/6/1
:boom: The GUI tests failed.
GUI Logs: (https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/index.html)
Server Logs: (https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/serverlog.log)
Stacktrace: (https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/stacktrace.log)
Screenshots:
- [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/screenshots/Delete_a_folder.png)
- [remove_an_account_connection.png](https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/screenshots/remove_an_account_connection.png)
- [remove_the_only_account_connection.png](https://cache.owncloud.com/public/owncloud/client/12357/guiReportUpload/screenshots/remove_the_only_account_connection.png)

<!-- id: pr-9863 -->

2022-07-06 10:08 UTC, dragotin approved these changes
Yeah.

2022-07-06 10:08 UTC, dragotin commented on src/gui/folderstatusmodel.cpp
>              emit dataChanged(index(folderIndex), index(folderIndex), roles);
I wonder if we should not check if `progress.status()` is different than the status that is stored currently. If it is **not** different we could save the `dataChanged()` emit completely, or not?

2022-07-06 10:08 UTC, dragotin commented on src/gui/folderstatusmodel.cpp
> +            _lastProgressUpdated = std::chrono::system_clock::now();
Ah, there is this QElapsedTimer which is very nice and neat...

2022-07-06 10:26 UTC, dragotin commented on src/gui/folderstatusmodel.cpp
> +            _lastProgressUpdated = std::chrono::system_clock::now();
Yes, progressUpdateTimeOutC would be a qint64, which would result in more clear code for me. But... yes.

2022-07-06 11:38 UTC, fmoc commented on src/gui/folderstatusmodel.cpp
> +            slotSetProgress(info, f);
You could implement this without having to use a lambda using `std::bind`.

2022-07-06 11:38 UTC, fmoc commented on src/gui/folderstatusmodel.cpp
> +        for (int i = 0; i < _folders.count(); ++i) {
Combination of `std::distance` and `std::find_first_of`?

2022-07-06 14:39 UTC, fmoc commented on changelog/unreleased/9836
> +This should reduce the probability for timeouts when downloading vfs files in the Windows explorer.
```suggestion
Enhancement: Run VFS downloads with a high priority

This should reduce the probability for timeouts when downloading VFS files in the Windows explorer.
```

2022-07-06 16:57 UTC, merged