Work/performance
owncloud/client pull request #9910
Opened 2022-07-12 12:15 UTC by TheOneRing

2022-07-12 12:16 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12477/6/1

<details>


</details>


<!-- id: pr-9910 -->

2022-07-12 12:58 UTC, TheOneRing commented on test/csync/vio_tests/check_vio_ext.cpp
> -    QByteArray result;
Not sure about the value of that unit test by now.....

2022-07-22 10:28 UTC, saw-jan commented
CI stopped with the following message:
```bash
starting tests
11:21:42:280 Info: Starting server of Squish version 6.7.3 Alpha.
11:21:42:288 Info: Listening on 0.0.0.0:4322
11:21:42:288 Info: Listening on ws://127.0.0.1:45009?zWKcD9u1ONE8SoLEWr_N
11:21:42:288 Info: Announcing server presence via SSDP 
```
Tests are not running. Restarted CI.

2022-07-26 12:40 UTC, fmoc requested changes

2022-07-26 12:40 UTC, fmoc commented on src/csync/vio/csync_vio_local_win.cpp
> +  if (vfs && vfs->statTypeVirtualFile(file_stat.get(), &handle->ffd)) {
The indentation is more off than it used to be. Please revise and if necessary fix for the entire file once and for all.

2022-07-26 12:48 UTC, fmoc approved these changes
Indentation mess will be fixed in follow-up PR.

2022-07-26 12:48 UTC, merged