Throttle folder status updates in general
owncloud/client pull request #9919
Opened 2022-07-14 10:57 UTC by TheOneRing

In #9863 we started throtteling the the ui updates during sync, this throttles the updates even more.

2022-07-14 11:33 UTC, fmoc commented on src/gui/folderstatusmodel.cpp
> +    if (std::chrono::steady_clock::now() - folder._lastProgressUpdated > progressUpdateTimeOutC) {
You lost the comment above this line. I think you should explain your thinking here, though. It'll help future developers greatly to understand why this is implemented the way it is.

2022-07-14 11:47 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12503/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12503/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12503/guiReportUpload/serverlog.log

Screenshots:
- [change_collaborator_permissions_of_a_file_&_folder.png](https://cache.owncloud.com/public/owncloud/client/12503/guiReportUpload/screenshots/change_collaborator_permissions_of_a_file_&_folder.png)
- [logging_out.png](https://cache.owncloud.com/public/owncloud/client/12503/guiReportUpload/screenshots/logging_out.png)
- [login_after_loggin_out.png](https://cache.owncloud.com/public/owncloud/client/12503/guiReportUpload/screenshots/login_after_loggin_out.png)

</details>


<!-- id: pr-9919 -->

2022-07-20 10:21 UTC, fmoc requested changes

2022-07-20 10:21 UTC, fmoc commented on changelog/unreleased/9919
> +Enhancement: Reduce cpu load during discover
```suggestion
Enhancement: Reduce CPU load during discovery
```

2022-07-21 11:36 UTC, fmoc approved these changes

2022-07-21 12:04 UTC, merged