Use more generic message when asking the user to authenticate
owncloud/client pull request #9931
Opened 2022-07-20 09:51 UTC by TheOneRing

![image](https://user-images.githubusercontent.com/200626/179961696-c4c68339-3efb-4658-b74a-380257433c16.png)

Fixes: #9896

2022-07-20 10:23 UTC, fmoc requested changes

2022-07-20 10:23 UTC, fmoc commented on src/gui/askforoauthlogindialog.cpp
> +    _ui->label->setText(tr("The account %1 is currently logged out.\n\nProceed to authenticate using your browser %2.").arg(accountPtr->displayName(), Theme::instance()->appNameGUI()));
Grammatically this makes no sense. Maybe `Proceed to authenticate to %2 using your browser.`? But then again, what's the advantage over the old message?

2022-07-20 11:09 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12540/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/serverlog.log

Screenshots:
- [File_with_spaces_in_the_name_can_sync.png](https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/screenshots/File_with_spaces_in_the_name_can_sync.png)
- [logging_out.png](https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/screenshots/logging_out.png)
- [simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_password_and_expiration_date.png)
- [simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12540/guiReportUpload/screenshots/simple_sharing_of_file_and_folder_by_public_link_with_expiration_date.png)

</details>


<!-- id: pr-9931 -->

2022-07-21 11:39 UTC, fmoc approved these changes
Feel free to merge, or further improve the message.

2022-07-21 11:39 UTC, fmoc commented on src/gui/askforoauthlogindialog.cpp
> +    _ui->label->setText(tr("The account %1 is currently logged out.\n\nProceed to authenticate using your browser.").arg(accountPtr->displayName()));
I think some "Please [...]" is missing in that sentence. I guess "Please authenticate using your browser" would do.

2022-07-21 12:33 UTC, merged