Fix changed during upload timeout
owncloud/client pull request #9932
Opened 2022-07-20 10:15 UTC by TheOneRing

Fixes: #9924

2022-07-20 10:43 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12537/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12537/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12537/guiReportUpload/serverlog.log

Screenshots:
- [Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12537/guiReportUpload/screenshots/Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png)
- [sharee_edits_content_of_files_shared_by_sharer.png](https://cache.owncloud.com/public/owncloud/client/12537/guiReportUpload/screenshots/sharee_edits_content_of_files_shared_by_sharer.png)

</details>


<!-- id: pr-9932 -->

2022-07-21 11:20 UTC, fmoc requested changes

2022-07-21 11:20 UTC, fmoc commented on changelog/unreleased/9924
> +We fixed another issue where changes during an upload could cause the file to be ignored for a increasing amount of time.
```suggestion
We fixed another issue where changes during an upload could cause the file to be ignored for an increasing amount of time.
```

2022-07-21 11:20 UTC, fmoc commented on src/libsync/propagateupload.h
> +    static QString fileChangedMessage();
Should be `const`.

2022-07-21 11:36 UTC, fmoc approved these changes

2022-07-21 12:04 UTC, merged