Cleanup checksum handling
owncloud/client pull request #9944
Opened 2022-07-21 15:50 UTC by TheOneRing

Looks like this change requires gcc > 10

2022-07-22 09:03 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12581/6/1

<details>


</details>


<!-- id: pr-9944 -->

2022-07-26 13:50 UTC, fmoc requested changes

2022-07-26 13:50 UTC, fmoc commented on src/common/checksumalgorithms.h
> +    inline QByteArray calcCryptoHash(QIODevice *device, QCryptographicHash::Algorithm algo)
This could (and probably should) be a template, same goes for `toString`.

2022-07-26 13:50 UTC, fmoc commented on src/common/checksumalgorithms.h
> +        SHA3_256 = QCryptographicHash::Sha3_256,
Does the sorting have any practical effect? You're assigning the values from Qt, so we are using their sorting (except for the last 3 entries at least).

Edit: I see, priorities are handled below. I guess the comment is just stale. Perhaps you can clarify that this is just sorted for the reader here, and the real priorizing is done below.

2022-07-26 13:50 UTC, fmoc commented on src/common/checksums.cpp
> +    // usually not a good idea to use toUpper on a byte array but we only care for the id which has no special chars
Sounds like you really want to have an assertion there. Assumptions need to be verified.

2022-07-26 13:50 UTC, fmoc commented on src/common/checksumalgorithms.h
> +    inline QByteArray calcCryptoHash(QIODevice *device, QCryptographicHash::Algorithm algo)
Why not use your own enum here?

2022-07-26 13:58 UTC, TheOneRing commented on src/common/checksumalgorithms.h
> +        case Algorithm::Error:
As soon as I use default I'll no longer get compiler warnings about missing values.

2022-07-26 14:40 UTC, fmoc approved these changes

2022-07-26 15:13 UTC, merged