Use existing helper to display directory in file browser
owncloud/client pull request #9987
Opened 2022-08-01 20:42 UTC by fmoc

Should fix #9750 (which I have not been able to reproduce so far).

This change should reduce the cases in which we fall back to `QDesktopServices` to open a directory in the user's file manager on Linux. The helper in use should usually detach (orphan) the process from the parent process and therefore the AppImage runtime can exit just fine when the client is terminated.

Not sure if we need a changelog item, this possibly fixes an issue present in 2.10. However, we considered the AppImage support experimental there.

2022-08-01 21:15 UTC, ownclouders commented
Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12714/6/1

:boom: The GUI tests failed.

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12714/guiReportUpload/index.html

<details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12714/guiReportUpload/serverlog.log

Screenshots:
- [Sync_all_is_selected_by_default.png](https://cache.owncloud.com/public/owncloud/client/12714/guiReportUpload/screenshots/Sync_all_is_selected_by_default.png)
- [Sync_only_one_folder_from_the_server.png](https://cache.owncloud.com/public/owncloud/client/12714/guiReportUpload/screenshots/Sync_only_one_folder_from_the_server.png)

</details>


<!-- id: pr-9987 -->

2022-08-05 11:06 UTC, TheOneRing commented
As far as I can tell this doesn't solve the issue it just adds an other level of complexification.

2022-08-05 11:06 UTC, TheOneRing requested changes
nope

2022-08-05 12:22 UTC, closed without merging

2022-08-05 12:42 UTC, fmoc commented
@TheOneRing checked Qt's internal workflow, and this won't solve the problem. I  Fun fact: we found out we can replace the internal workflow of that helper with a much simpler D-Bus based solution even. A PR is on the way.